### PR TITLE
rename `defaultTheme` to `overrideTheme` and clarify it overrules and ignores prefers-color-scheme

### LINKED ISSUE #20: v1.1.0 not using preferred scheme in Chrome on Windows
I tried upgrading to version 1.1.0, but found that it did not respect my preferred color scheme, using Chrome on Windows. Changing the `<html>` tag to contain `theme="dark"` did work, but the "magic" was gone.

Reverting back to 1.0.9 resolved the issue and *it just works* again.

### PR DESCRIPTION
**Pull request by spawnia**
fixes https://github.com/tolking/vuepress-theme-default-prefers-color-scheme/issues/20

### CODE REVIEW

**Comment by jrappen** [comment]
@spawnia if you change the leading comment's text from `#20` to `fixes #20`, this will auto-close issue 20 upon merge.

**Comment by jrappen** [comment]
Thanks for your work.

It seems `defaultTheme` with the pre-`v1.1.0` behavior is now missing, though. Had you planned opening another pull request or will you append to this?

**Comment by spawnia** [comment]
> It seems `defaultTheme` with the pre-`v1.1.0` behavior is now missing, though. Had you planned opening another pull request or will you append to this?

Consider https://github.com/tolking/vuepress-theme-default-prefers-color-scheme/compare/v1.0.9...v1.1.0 - it looks like this functionality depended on a PostCSS plugin which was removed. I don't know how to make both work, so this is pretty much just a rename and clarification for a change in behaviour that was introduced in v1.1.0.

**Comment by jrappen** [comment]
@tolking Is there a reason you removed the postcss dependency? I'm still interested in bringing back v1.0.9 and earlier behavior.

**Comment by jrappen** [comment]
I noticed this pull request doesn't update the chinese docs. So those will still need to be worked on.

**Comment by spawnia** [comment]
> I noticed this pull request doesn't update the chinese docs. So those will still need to be worked on.

Unfortunately, my chinese skills are non-existent :)

**Comment by jrappen** [comment]
I assumed so, just a remark to keep that in mind.

**Comment by tolking** [comment]
Thanks, I will take care of the rest

**Comment by jrappen** [comment]
Thanks @tolking and @spawnia for your work. The v2.0.0 update is highly appreciated.

**Pull request merged**
