### PR TITLE
some minor fixes

### PR DESCRIPTION
**Pull request by jrappen**
- change from `js` to `diff` code blocks in migration docs
- readability English docs
- add some links to references

### CODE REVIEW

**Comment by jrappen** [comment]
⚠️ That workflow shouldn't attempt to deploy the docs built for testing. It naturally fails due to me not being authorized to push to your repo.

**Comment by tolking** [comment]
> ⚠️ That workflow shouldn't attempt to deploy the docs built for testing. It naturally fails due to me not being authorized to push to your repo.

thanks, I also found this problem.

**Comment by jrappen** [comment]
if you need help, let me know

**Comment by tolking** [comment]
Welcome PR
Maybe:
PR -› test the build
push master -› build and deploy

**Comment by jrappen** [comment]
Ok, I am busy now. Will give it a try later today.

**Pull request merged**
